language: node_js
node_js: 8
env:
  global:
    secure: waNrNVgzUM4zxLyVyFVfGyo9ofYt/JRjcS8bzGW3Zl1uuCMrhgozQ9RUwRmgBt8bvPQKjM91bGmED/A8PYbXPmOewW0opw+RfIBNCDZoFGxdfujE3+0rBcsz5qi+KQ9Ngv8k8kmtS4XliyK1FfgzFp+8O8NdvHd3FjywVLAJpQ8G10N4xrss1TzmcJUyQfh0CAqp8OUBvGiKTHGonJDNRnfk1rytCRXjAWdghnWPiaMtk6gy4+QUeFxHpku5hpA2GRfQGS9F5IRuCUe1s+p2U3W7dnglhlX+oOv1lIMPExSC78Kzo99i33vzMOWyUjAseDUZ9Ea9XgaOLgTQYHyOdzH6evBJrJHnAvRj9gKIgOiqTovxeUFczYHoj61176NT6t4NmH+XScDXxN6XLrdUDJY7h1K5swU0utUGB16SF74CSe0lmzzc4eaTYItEF42Gq4utFERkOQWBJCB1/tXb6Tm1XDxv3XS88bWKEZZd5XNla8PiKnopLxNjE+ciyBwn+k8orqJomRa6KzRSJkn/VGft+81ugxwVxaeqpg0wqp+G4KRll/GPMfIL4wQkV7SxtbChWYowvvcnalVsRvvhx1mMAKs6qRfGwHPx8uTNmkNqn9Wyva+9wX4oJ3NM5R+iUvv1n5RAJ6fNDdZVi5iepeLw1TFX7jW2zpVcLz8LhgU=
cache: yarn
before_deploy: rm yarn.lock
deploy:
  provider: script
  script: yarn now-deploy
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - yarn now-alias
  - yarn now-rm
notifications:
  email:
    recipients:
      - roger@sourcier.uk
    on_success: never
    on_failure: always
